#!/usr/bin/env bash

set -e # Exit if any fail
set -o pipefail

export ANSIBLE_NOCOWS=1
export ANSIBLE_STDOUT_CALLBACK=debug
unset ANSIBLE_VAULT_PASSWORD_FILE

if [ -z "$1" ]; then
  echo "You must specify a playbook to run"
  echo "   puter debian-chroot.yml"
  exit 1
fi

set -u # Error on unset vars

command -v ansible-playbook >/dev/null 2>&1 || {
  echo Ansible is not installed.
  echo Running 'sudo apt-get install ansible'
  sudo apt-get install ansible
}

command -v aptitude  >/dev/null 2>&1 || {
  echo Aptitude is not installed.
  echo Running 'sudo apt-get install aptitude'
  sudo apt-get install aptitude
}

ansible-playbook $1 -i hosts.ini --ask-become-pass --diff -v
