#!/usr/bin/env bash

set -e # Exit if any fail
set -o pipefail

export ANSIBLE_NOCOWS=1
export ANSIBLE_STDOUT_CALLBACK=debug
unset ANSIBLE_VAULT_PASSWORD_FILE

set -u # Error on unset vars

command -v ansible-playbook >/dev/null 2>&1 || {
  echo Ansible is not installed.
  echo Running 'sudo apt-get install ansible'
  sudo apt-get install ansible
}

ansible-playbook main.yml -i hosts.yml --diff -v
